# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
    ]
