# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20171130_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='title_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Category_img'),
        ),
    ]
