# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20171130_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_img',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
