# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(max_length=30),
        ),
    ]
